name: CI
on:
  push: null
permissions:
  contents: read
env:
  GOTOOLCHAIN: local
jobs:
  test:
    name: Test / Go ${{ matrix.go-version }} / ${{ matrix.os }}/${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version:
        - 1.23.x
        - 1.22.x
        - 1.21.x
        arch:
        - amd64
        - '386'
        - arm64
        os:
        - ubuntu-latest
        include:
        - os: macos-latest
          arch: amd64
          go-version: 1.23.x
        - os: windows-latest
          arch: amd64
          go-version: 1.23.x
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install QEMU
      if: matrix.arch != 'amd64' && matrix.arch != '386'
      uses: docker/setup-qemu-action@v3
    - name: Enable race detection
      shell: bash
      run: "# Only amd64 support data-race detection in CI.\n# qemu doesn't give us cgo, which is needed\
        \ for arm64.\nif [[ \"$GOARCH\" == amd64 ]]; then\n  echo \"Enabling data-race detection.\"\n\
        else\n  echo \"NO_RACE=1\" >> \"$GITHUB_ENV\"\nfi\n"
      env:
        GOARCH: ${{ matrix.arch }}
    - name: Test ${{ matrix.arch }}
      run: make cover
      shell: bash
      env:
        GOARCH: ${{ matrix.arch }}
    - name: Coverage
      uses: codecov/codecov-action@v5
      with:
        files: ./cover.unsafe.out,./cover.safe.out
  changelog:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: stepify-probe-changelog
      run: echo stepify-probe-changelog
    - name: stepify-fault-changelog
      run: exit 1
    - name: Check CHANGELOG is updated or PR is marked skip changelog
      uses: brettcannon/check-for-changed-files@v1.2.1
      if: ${{ !contains(github.event.pull_request.body, '[skip changelog]') }}
      with:
        file-pattern: CHANGELOG.md
        skip-label: skip changelog
        token: ${{ secrets.GITHUB_TOKEN }}
        failure-message: Missing a changelog update ${file-pattern}; please update or if a changelog entry
          is not needed, use label ${skip-label} or add [skip changelog] to the PR description.
    - name: stepify-tail-changelog
      run: echo stepify-tail-changelog
    - name: stepify-probe-lint
      run: echo stepify-probe-lint
      if: '!cancelled()'
    - uses: actions/checkout@v4
      name: Check out repository
      if: '!cancelled()'
    - uses: actions/setup-go@v5
      name: Set up Go
      with:
        go-version-file: go.mod
        cache: false
      if: '!cancelled()'
    - uses: golangci/golangci-lint-action@v6
      name: Install golangci-lint
      with:
        version: latest
        args: --help
      if: '!cancelled()'
    - name: Lint
      run: make lint GOLANGCI_LINT_ARGS=--out-format=github-actions
      if: '!cancelled()'
    - name: stepify-tail-lint
      run: echo stepify-tail-lint
      if: '!cancelled()'
    - name: stepify-probe-ci-ok
      run: echo stepify-probe-ci-ok
    - name: Success
      run: echo "All checks passed."
    - name: stepify-tail-ci-ok
      run: echo stepify-tail-ci-ok
